//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L_CRM_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> BillAmount { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string Address { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CustomerType CustomerType { get; set; }
    }
}
